### PR TITLE
feat(search): add search functionality and fix minor issues

### LINKED ISSUE #84: Implement Search functionality for accounts, blocks and extrinsics

### LINKED ISSUE #88: Pagination buttons are not functional
The numbered pagination buttons are not functional. Not sure if this is yet to be implemented or if they aren't working. Either way, creating the ticket to capture the issue.

image

### LINKED ISSUE #90: Extrinsic table column mis-labeled
The first column of the extrinsic table on the Extrinsics page is labeled as "Block" but should be "Extrinsic".

image

### PR DESCRIPTION
**Pull request by natachadelarosa**
close #84 
close #88 
close #90

### CODE REVIEW

File: client/src/common/components/SearchBar.tsx [hunk 1]
```diff
@@ -1,100 +1,135 @@
...
-              required
-            />
-            <button
-              type='submit'
-              className='absolute right-1 md:right-2.5 bottom-0 focus:ring-4 focus:outline-none font-medium rounded-lg text-sm px-4 py-2 '
+    <Formik
+      initialValues={initialValues}
+      validationSchema={searchValidationSchema}
+      onSubmit={(values) => {
+        console.log(values)
```
Comment (isSerge) [inline client/src/common/components/SearchBar.tsx:47]: forgot to remove it?

File: client/src/layout/components/NotFound.tsx [hunk 2]
```diff
@@ -0,0 +1,38 @@
+import { FC } from 'react'
+import { useNavigate } from 'react-router-dom'
+
+// common
+import { INTERNAL_ROUTES } from 'common/routes'
+
+const NotFound: FC = () => {
+  const navigate = useNavigate()
+
+  const handleNavigate = (url: string) => {
```
Comment (isSerge) [inline client/src/layout/components/NotFound.tsx:10]: seems like we can just use `navigate`

**Review by isSerge — COMMENTED** [review]
I really liked `useSearch` implementation, left some minor comments

**Review by isSerge — APPROVED** [review]
