### PR TITLE
fix(url): update selected network to url matching network if is diffe…

### LINKED ISSUE #191: Inconsistent UI when alternating Gemini-2 and Gemini-3 links
## Expected Behavior

When I open a link pointing to a specific `Gemini-2a` or `Gemini-3d` account, I expect to see the correct information (balance, nonce).
Further, the dropdown menu in the top-right corner reflects which network I'm using.

## Current Behavior

If I am browsing `Gemini-2a` in the explorer, and then I click an external link pointing to a `Gemini-3b`, the UI still shows `Gemini-2a` data. I can fix the issue only if I reload the page.

## Steps to Reproduce

1. Browse https://explorer.subspace.network
2. Select `Gemini-2a` from the dropdown menu
3. Paste the link `https://explorer.subspace.network/#/gemini-3c/accounts/st6iwqnxNab6JUawtmqUmftG2oSsKoTaWzbg9PxdWrWw5C6Th`
4. The data is still from Gemini-2a, and the dropdown menu doesn't change

## Context (Environment)

While this is a corner case (we can't expect many users to change networks so often), it introduces a confounding behavior if the wallet address is the same on both networks.

### PR DESCRIPTION
**Pull request by natachadelarosa**
…rent from the selected

closes #191

### CODE REVIEW

File: client/src/App.tsx [hunk 1]
```diff
@@ -59,6 +59,27 @@ const LegacyGemini2Redirect: FC<{ path: string }> = ({ path }) => {
   return <Navigate replace to={to} />
 }
 
+const UpdateSelectedChainByPath: FC = () => {
```
Comment (isSerge) [inline client/src/App.tsx:62]: since it does not render anything does it have to be a component?

**Review by isSerge — APPROVED** [review]

**Comment by isSerge** [comment]
👍
