### PR TITLE
fix(json): show just objects below 5 items

### LINKED ISSUE #218: Fix json view display
Currently, the extrinsic JSON view shows  the JSON not collapsed by default
image

This looks bad is the JSON is too long, and for that reason needs to be fixed to show just a small peak of the JSON, and if the user wants to view more, they can interact with the component to do so.

### PR DESCRIPTION
**Pull request by natachadelarosa**
close #218

### CODE REVIEW

File: client/src/common/components/Arguments.tsx [hunk 1]
```diff
@@ -28,7 +28,14 @@ const theme = {
 const Arguments: FC<Props> = ({ args }) => {
   return (
     <div data-testid='testJsonDisplay' className='dark:text-white text-[#282929]'>
-      <ReactJson src={args || {}} iconStyle='circle' theme={theme} />
+      <ReactJson
+        src={args || {}}
+        iconStyle='circle'
+        theme={theme}
+        shouldCollapse={(field) => {
+          return field.type === 'object' && Object.entries(field.src).length > 5 ? true : false
```
Comment (isSerge) [inline client/src/common/components/Arguments.tsx:36]: very neat

**Review by isSerge — APPROVED** [review]
