### PR TITLE
fix(extrinsic): show correct module and call

### LINKED ISSUE #215: Extrinsic page: `module` and `call` have the same value
1. Go to an extrinsic page, for example, https://explorer.subspace.network/#/gemini-3c/extrinsics/0000745465-000007-61311
2. `module` and `call` have the same value: `Subspace.vote` 
image

Expected:
module: Subspace
call: Vote

### PR DESCRIPTION
**Pull request by natachadelarosa**
close #215

### CODE REVIEW

File: client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx [hunk 1]
```diff
@@ -59,8 +61,10 @@ const ExtrinsicDetailsCard: FC<Props> = ({ extrinsic, isDesktop = false }) => {
                     {isDesktop ? extrinsic.hash : shortString(extrinsic.hash)}
                   </CopyButton>
                 </StyledListItem>
-                <StyledListItem title='Module'>{extrinsic.name}</StyledListItem>
-                <StyledListItem title='Call'>{extrinsic.name}</StyledListItem>
+                <StyledListItem title='Module'>{module}</StyledListItem>
+                <StyledListItem title='Call' childrenAdditionalClassNames='capitalize'>
```
Comment (isSerge) [inline client/src/Extrinsic/components/ExtrinsicDetailsCard.tsx:65]: can't we add `capitalize` to the item directly instead of passing it as a prop?

**Review by isSerge — APPROVED** [review]
👍
